version: '3.4'
services:
  api:
    container_name: pms-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    ports:
    - 80:80
    volumes:
    - ./:/var/www/html
    networks:
    - pmsNetwork

  db:
    image: mariadb
    restart: 'no'
    ports:
    - 3306:3306
    volumes:
    - ./docker_data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  pmsNetwork:
    driver: bridge
