version: '3.4'
services:
  api:
    container_name: pms-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    ports:
    - 80:80
    volumes:
    - ./:/var/www/html
    networks:
    - pmsNetwork

networks:
  pmsNetwork:
    driver: bridge
